#!/bin/sh
cat <<EOF
<table cellspacing="0" cellpadding="0">
<colgroup>
   <col width="240"/>
   <col width="*"/>
</colgroup>
<tr height="1" class="bottom">
   <td>
      <a name="top" id="top">
      <img border="0" src="/images/space.gif" height="1" width="250" align="left" hspace="0" vspace="0"/>
      </a>
   </td><td>
      <img border="0" src="/images/space.gif" height="1" width="250" align="left" hspace="0" vspace="0"/>
   </td>
</tr><tr id="header">
   <td id="title">
      <a onclick="javascript:select('$FA_NEXT_PAGE'); return false;" href="/refresh">
      <img src="/images/Freetz.png" alt="logo" border="0" class="logo"/></a>
   </td>
   <td id="quote" nowrap>
      <p class="version">
EOF
getText FW001
echo -n "&nbsp;$FA_VERSION&nbsp;"
cat /etc/.freetz-version
echo -n '</p><p class="topic">'
getText FA001
cat <<EOF
      </p>
   </td>
</tr><tr valign="top">
   <td id="sidebar">
      <img border="0" src="/images/space.gif" height="800" width="1" align="left" hspace="0" vspace="0"/>
      <div>
EOF
. ../tools/mainnavi
cat <<EOF
         <div class="container">
            <div class="headline">Lizenz</div>
            <div id="gpl">
               <a href="http://www.gnu.org/licenses/old-licenses/gpl-2.0.html" target="_blank">
               <img border="0" src="/images/gplv2-127x127.png" width="127" height="127" alt="GPL"/>
               </a>
            </div>
         </div>
      </div>
   </td>
   <td id="bodycontent">
      <div id="topmenu">
         <table>
            <tr>
               <td class="headline">
EOF
. ../tools/subnavi 
cat <<EOF
               </td>
            </tr>
         </table>
      </div>
      <form name="application" target="main" method="get" action="$SCRIPT_NAME$FA_NEXT_PAGE">
      <div id="pagecontent">
EOF
. ../tools/servePage
cat <<EOF
      </div>
      </form>
   </td>
</tr><tr>
   <td class="bottom">&nbsp;</td>
   <td>
      <div id="footer">
         <table>
            <colgroup>
               <col width="240"/>
               <col width="*"/>
            </colgroup>
            <tr>
               <td class="bottom"><img src="/images/space.gif" height="1" width="245" align="left" hspace="0" vspace="0"/></td>
               <td class="footer">
EOF
getText CR001
cat <<EOF
               </td>
            </tr>
         </table>
      </div>
   </td>
</tr>
</table>
EOF
