#!/bin/sh -v
cd "$(dirname "$0")"
sess=/var/lib/webif
mkdir -p "$sess"
chmod 700 "$sess"
env - PATH="$PWD/bin:$PATH" session_dir="$sess" TRACE="con*" httpd -c "$PWD/etc/httpd.conf" -fvv -p 8181 -h "$PWD/htdocs"
