#!/bin/sh
# Upload handler
if [ -z "${REQUEST_METHOD+1}" -o $# -lt 1 ]; then
    echo "May only be called as an upload handler" >&2
    exit 1
fi
export UPLOAD_FIFO=$1
exec /usr/bin/haserl --accept-all "$0" < /dev/null 3>&1 1> /dev/null
<% exec 1>&3 3>&-
#
# This script is a hybrid: The shell code preceding this comment will make
# haserl process the following code.
#
%><% create_session=0; source "${PWD%%/htdocs/*}/controller" %>
