#!/bin/sh
genBox() {
   read title
   echo -n '<div class="container"><div class="headline">'
   getText $title
   echo -n '</div>'
   while read link name; do
         echo -n '<div class="entry"><a onclick="javascript:select('
         echo -n "'$link'); return false;\" href=\"$link\">"
         getText $name
         echo -n '</a></div>'
   done
   echo '</div>'
}

genBox <<EOF
IN000
/html/status   IN001
/html/online   IN002
/html/calls    IN003
/html/book     IN004
/html/usb      IN005
/html/events   IN006
/html/energy   IN007
/html/dsl      IN008
/html/info     IN009
EOF

genBox <<EOF
TEL00
/html/redir    TEL01
/html/wakeup   TEL02
/html/dect     TEL03
/html/teldev   TEL04
/html/siplist  TEL05
/html/route    TEL06
EOF

genBox <<EOF
N0000
/html/network  N0001
/html/kids     N0002
/html/prio     N0003
/html/portfw   N0004
/html/nas      N0005
/html/route    N0006
/html/services N0007
EOF

genBox <<EOF
WL000
/html/wlan     WL001
EOF

genBox <<EOF
SY000
/html/system   SY001
/html/logs     SY007
/html/bakrest  SY002
/html/update   SY003
/html/reboot   SY004
/html/connect  SY005
/html/reset    SY006
EOF

