#!/bin/sh
cat << EOF
<input type="hidden" name="page" value="/index.html"/>
<input type="hidden" name="token" value="${SESSIONID}"/>
<input type="hidden" name="sid" value="${FA_SID}"/>
<input type="hidden" name="usrreq" value="${FA_USRREQ}"/>
EOF

page="${FA_BASE}${FA_NEXT_PAGE}"

if [ -e "${page}.html" ]; then
   cat "${page}.html"
elif [ -x "${page}.cgi" ]; then
   "${page}.cgi"
elif [ -x "${page}.hsl" ]; then
   "${page}.hsl" < /dev/null
elif [ -x "${page}.sh" ]; then
   "${page}.sh"
elif [ -s "${page}.avm" -o -d "${page}" -o -d "${page}.${FA_THEME}" ]; then
   "$FA_WORK_FILE" < /dev/null 
#   rm -f "$FA_WORK_FILE"
fi  
if true; then # during development
   echo '<div id="environment" class="source">'
   printenv() {
   echo '<table class="styledTable"><tr class="header"><td><h3>Name</h3></td><td><h3>Wert</h3></td></tr>'   
   while read name value; do
   echo '<tr class="row"><td>'$name'</td><td>'$value'</td></tr>'
   done   
   echo '</table>'
   }
   env | sort | sed 's/=/ /' | printenv 
   echo '</div>'
fi
