#!/bin/sh
source logging.lib

tmp="/var/tmp/$PAGE_NAME.html"
page="${FA_BASE}${FA_NEXT_PAGE}"

if [ -d "${page}.$FA_THEME" -o -d "${page}" ]; then
   log_info "have to process directory ..."
   base="${page}"
   if [ -d "${page}.$FA_THEME" ]; then
      base="${page}.$FA_THEME"
   fi
   log_info "directory is [$base]"
   # FIXME: parallel requests will corrupt the temp file
   echo '#!/usr/bin/haserl' > "$tmp"
   for f in $base/*; do
      log_info "processing file [$f]"                   
      case $f in
      *.avm)
         ./webcm "getpage=$f" | grep -v '^#!' >> "$tmp"
         ;;
      *.html)
         cat "$f" >> "$tmp"
         ;;
      *.hsl)
         cat "$f" | grep -v '^#!' >> "$tmp"
         ;;
      *.sh)
         $f >> "$tmp"
         ;;
      esac
   done   
   chmod +x "$tmp"
elif [ -s "${page}.avm" ]; then
   log_info "page [${page}] is avm-page"
   ./webcm "getpage=${page}.avm" | grep -v '^#!' > "$tmp"
   chmod +x "$tmp"
fi
